Repository fga-eps-mds/2020.1-Grupo6, pull requests merged in 2020-09, with the labels that each got.

#14 Updated README with member information
  README.md
Labels: Treinamento

#16 Include developer info at README
  README.md
Labels: Treinamento

#27 [WIP] Issue 06 artefatos organizacionais
  .github/PR_TEMPLATE.md
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/Roadmaps/product/product_roadmap_v0.png
  docs/Roadmaps/product/product_roadmap_v1.jpg
  docs/Roadmaps/product/product_roadmap_v1.pdf
  docs/Roadmaps/product/product_roadmap_v2.jpg
  docs/Roadmaps/roles/roles_roadmap_v1.jpg
  docs/Roadmaps/roles/roles_roadmap_v1.pdf
  docs/Roadmaps/roles/roles_roadmap_v2.jpg
  docs/about.md
  docs/artefatos_organizacionais/DGC.md
  docs/org_artifacts/img/branches.png
  docs/org_artifacts/software_configuration_management.md
  docs/org_artifacts/vision_doc.md
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/files_and_folders.md
  docs/policies/img/branches.png
  docs/policies/img/issue_assign.png
  docs/policies/img/issue_info.png
  docs/policies/img/issue_labels_1.png
  docs/policies/img/issue_labels_2.png
  docs/policies/img/issue_milestone.png
  docs/policies/img/issue_templates.png
  docs/policies/img/pr_assign.png
  docs/policies/img/pr_labels.png
  docs/policies/img/pr_milestone.png
  docs/policies/img/pr_reviewers.png
  docs/policies/img/pr_template.png
  docs/policies/issues.md
  docs/policies/pull_requests.md
  docs/pull_request_template.md
Labels: Documentação, EPS, Organização, Sprint 2

#37 Issue 32 elicitar requisitos
  README.md
  docs/Roadmaps/roadmap.md
  docs/about.md
  docs/index.md
  docs/org_artifacts/img/mind_map.png
  docs/org_artifacts/requirements_engineering.md
  mkdocs.yml
Labels: Documentação, EPS, User Story

#39 [Issue_38][WIP] Create TAP
  docs/org_artifacts/tap.md
  mkdocs.yml
Labels: Documentação, EPS, Sprint 3, User Story

#35 [WIP]Update item 4
  docs/org_artifacts/vision_doc.md
Labels: Documentação, MDS, Sprint 3

#41 [Issue 40][WIP] Sprints Reports
  .github/ISSUE_TEMPLATE/issue_template.md
  docs/_sidebar.md
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/files_and_folders.md
  docs/policies/issues.md
  docs/policies/pull_requests.md
  docs/roadmaps/product/product_roadmap_v0.png
  docs/roadmaps/product/product_roadmap_v1.jpg
  docs/roadmaps/product/product_roadmap_v1.pdf
  docs/roadmaps/product/product_roadmap_v2.jpg
  docs/roadmaps/roadmap.md
  docs/roadmaps/roles/roles_roadmap_v1.jpg
  docs/roadmaps/roles/roles_roadmap_v1.pdf
  docs/roadmaps/roles/roles_roadmap_v2.jpg
  docs/sprints/sprint0.md
  docs/sprints/sprint1.md
  docs/sprints/sprint2.md
  docs/sprints/sprint3.md
  mkdocs.yml
Labels: Documentação, EPS, Organização, Sprint 3, Technical Story

#48 Issue_47 Atualização dos requisitos do doc de visão
  docs/org_artifacts/vision_doc.md
Labels: Documentação, MDS, Sprint 3, User Story

#51 [Issue_50] Adds section 3 to the vision document
  docs/org_artifacts/vision_doc.md
Labels: Documentação, MDS, Sprint 3

#57 [Issue_56] Adds section 2 to the vision document
  docs/org_artifacts/vision_doc.md
Labels: Documentação, MDS, Sprint 4

#58 [Issue_54] Added topic 6 in the vision document.
  docs/org_artifacts/vision_doc.md
Labels: Documentação, MDS, Sprint 3

#61 [Issue_60] Update item 4 at doc_vision
  docs/org_artifacts/vision_doc.md
Labels: Documentação, MDS, Sprint 4, User Story

#63 [Issue_62] Use case document section 4
  docs/org_artifacts/architecture_doc.md
  docs/org_artifacts/img/use_case_diagram.png
Labels: Documentação, MDS, Sprint 4, User Story

#72 Issue 47 recursos doc visao
  docs/org_artifacts/vision_doc.md
Labels: Documentação, EPS, Sprint 3, User Story

#67 [Issue_66][WIP] Topico 5 doc de arquitetura
  docs/org_artifacts/architecture_doc.md
  docs/org_artifacts/img/front_end_packages.png
  docs/org_artifacts/img/mvc.png
  docs/org_artifacts/img/routes.png
  docs/org_artifacts/img/uml_model.png
Labels: Documentação, MDS, Sprint 4, User Story

#69 [Issue_68]Added topic 3 in the architecture document.
  docs/org_artifacts/architecture_doc.md
  docs/org_artifacts/img/use_case_diagram.png
Labels: Documentação, MDS, Sprint 4, User Story

#70 [Issue 40][WIP]Sprints Reports
  docs/org_artifacts/communication_plan.md
  docs/sprints/est_sprint.md
  docs/sprints/sprint1.md
  docs/sprints/sprint2.md
  docs/sprints/sprint3.md
  docs/sprints/sprint4.md
  mkdocs.yml
Labels: Documentação, EPS, Sprint 4

#78 Adds backlog version 2
  docs/org_artifacts/architecture_doc.md
  docs/org_artifacts/requirements_engineering.md
Labels: Documentação, EPS, Organização, Refatoração, Sprint 4
